# Generated by Django 5.1.7 on 2025-05-14 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mergenceApp', '0003_emergencyreport_ticket_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('hotline_number', models.CharField(max_length=20)),
                ('hotline_category', models.CharField(choices=[('paramedics', 'Paramedics'), ('fire', 'Fire & Rescue'), ('law', 'Law Enforcement'), ('utility', 'Utility & Electrical')], max_length=20)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
