# Generated by Django 5.1.7 on 2025-05-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mergenceApp', '0002_emergencyreport_created_at_emergencyreport_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyreport',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
