# Generated by Django 5.1.7 on 2025-05-15 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mergenceApp', '0004_partnerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
